/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * BeHired API - Tinder-style job matching platform
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Applicant,
  AuthResponse,
  CreateJobRequest,
  EmployerSwipeRequest,
  ErrorResponse,
  GetJobsParams,
  HealthStatus,
  Job,
  LoginRequest,
  Match,
  MessageResponse,
  RegisterRequest,
  SwipeRequest,
  SwipeResponse,
  UpdateProfileRequest,
  UserProfile,
} from "./types";

import { customFetch } from "./fetch";
import type { ErrorType, BodyType } from "./fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns server health status
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Register a new user
 */
export const getRegisterUserUrl = () => {
  return `/api/auth/register`;
};

export const registerUser = async (
  registerRequest: RegisterRequest,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getRegisterUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerRequest),
  });
};

export const getRegisterUserMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUser>>,
    TError,
    { data: BodyType<RegisterRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  { data: BodyType<RegisterRequest> },
  TContext
> => {
  const mutationKey = ["registerUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerUser>>,
    { data: BodyType<RegisterRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return registerUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerUser>>
>;
export type RegisterUserMutationBody = BodyType<RegisterRequest>;
export type RegisterUserMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Register a new user
 */
export const useRegisterUser = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUser>>,
    TError,
    { data: BodyType<RegisterRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  { data: BodyType<RegisterRequest> },
  TContext
> => {
  return useMutation(getRegisterUserMutationOptions(options));
};

/**
 * @summary Login user
 */
export const getLoginUserUrl = () => {
  return `/api/auth/login`;
};

export const loginUser = async (
  loginRequest: LoginRequest,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getLoginUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginRequest),
  });
};

export const getLoginUserMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    { data: BodyType<LoginRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  const mutationKey = ["loginUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginUser>>,
    { data: BodyType<LoginRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return loginUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginUser>>
>;
export type LoginUserMutationBody = BodyType<LoginRequest>;
export type LoginUserMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Login user
 */
export const useLoginUser = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    { data: BodyType<LoginRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  return useMutation(getLoginUserMutationOptions(options));
};

/**
 * @summary Logout user
 */
export const getLogoutUserUrl = () => {
  return `/api/auth/logout`;
};

export const logoutUser = async (
  options?: RequestInit,
): Promise<MessageResponse> => {
  return customFetch<MessageResponse>(getLogoutUserUrl(), {
    ...options,
    method: "POST",
  });
};

export const getLogoutUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutUser>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logoutUser>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["logoutUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logoutUser>>,
    void
  > = () => {
    return logoutUser(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof logoutUser>>
>;

export type LogoutUserMutationError = ErrorType<unknown>;

/**
 * @summary Logout user
 */
export const useLogoutUser = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutUser>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof logoutUser>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutUserMutationOptions(options));
};

/**
 * @summary Get current user session
 */
export const getGetCurrentUserUrl = () => {
  return `/api/auth/me`;
};

export const getCurrentUser = async (
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getGetCurrentUserUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetCurrentUserQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({
    signal,
  }) => getCurrentUser({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCurrentUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUser>>
>;
export type GetCurrentUserQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get current user session
 */

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCurrentUserQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get the current user's profile
 */
export const getGetMyProfileUrl = () => {
  return `/api/profile`;
};

export const getMyProfile = async (
  options?: RequestInit,
): Promise<UserProfile> => {
  return customFetch<UserProfile>(getGetMyProfileUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMyProfileQueryKey = () => {
  return [`/api/profile`] as const;
};

export const getGetMyProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyProfile>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyProfile>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyProfile>>> = ({
    signal,
  }) => getMyProfile({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyProfile>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMyProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyProfile>>
>;
export type GetMyProfileQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get the current user's profile
 */

export function useGetMyProfile<
  TData = Awaited<ReturnType<typeof getMyProfile>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyProfile>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMyProfileQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update the current user's profile
 */
export const getUpdateMyProfileUrl = () => {
  return `/api/profile`;
};

export const updateMyProfile = async (
  updateProfileRequest: UpdateProfileRequest,
  options?: RequestInit,
): Promise<UserProfile> => {
  return customFetch<UserProfile>(getUpdateMyProfileUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProfileRequest),
  });
};

export const getUpdateMyProfileMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMyProfile>>,
    TError,
    { data: BodyType<UpdateProfileRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMyProfile>>,
  TError,
  { data: BodyType<UpdateProfileRequest> },
  TContext
> => {
  const mutationKey = ["updateMyProfile"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMyProfile>>,
    { data: BodyType<UpdateProfileRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return updateMyProfile(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMyProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMyProfile>>
>;
export type UpdateMyProfileMutationBody = BodyType<UpdateProfileRequest>;
export type UpdateMyProfileMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Update the current user's profile
 */
export const useUpdateMyProfile = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMyProfile>>,
    TError,
    { data: BodyType<UpdateProfileRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateMyProfile>>,
  TError,
  { data: BodyType<UpdateProfileRequest> },
  TContext
> => {
  return useMutation(getUpdateMyProfileMutationOptions(options));
};

/**
 * @summary Get job listings for swiping
 */
export const getGetJobsUrl = (params?: GetJobsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/jobs?${stringifiedParams}`
    : `/api/jobs`;
};

export const getJobs = async (
  params?: GetJobsParams,
  options?: RequestInit,
): Promise<Job[]> => {
  return customFetch<Job[]>(getGetJobsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetJobsQueryKey = (params?: GetJobsParams) => {
  return [`/api/jobs`, ...(params ? [params] : [])] as const;
};

export const getGetJobsQueryOptions = <
  TData = Awaited<ReturnType<typeof getJobs>>,
  TError = ErrorType<unknown>,
>(
  params?: GetJobsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getJobs>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetJobsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getJobs>>> = ({
    signal,
  }) => getJobs(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getJobs>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetJobsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getJobs>>
>;
export type GetJobsQueryError = ErrorType<unknown>;

/**
 * @summary Get job listings for swiping
 */

export function useGetJobs<
  TData = Awaited<ReturnType<typeof getJobs>>,
  TError = ErrorType<unknown>,
>(
  params?: GetJobsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getJobs>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetJobsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new job listing (employers only)
 */
export const getCreateJobUrl = () => {
  return `/api/jobs`;
};

export const createJob = async (
  createJobRequest: CreateJobRequest,
  options?: RequestInit,
): Promise<Job> => {
  return customFetch<Job>(getCreateJobUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createJobRequest),
  });
};

export const getCreateJobMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createJob>>,
    TError,
    { data: BodyType<CreateJobRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createJob>>,
  TError,
  { data: BodyType<CreateJobRequest> },
  TContext
> => {
  const mutationKey = ["createJob"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createJob>>,
    { data: BodyType<CreateJobRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createJob(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateJobMutationResult = NonNullable<
  Awaited<ReturnType<typeof createJob>>
>;
export type CreateJobMutationBody = BodyType<CreateJobRequest>;
export type CreateJobMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Create a new job listing (employers only)
 */
export const useCreateJob = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createJob>>,
    TError,
    { data: BodyType<CreateJobRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createJob>>,
  TError,
  { data: BodyType<CreateJobRequest> },
  TContext
> => {
  return useMutation(getCreateJobMutationOptions(options));
};

/**
 * @summary Get job details
 */
export const getGetJobByIdUrl = (id: string) => {
  return `/api/jobs/${id}`;
};

export const getJobById = async (
  id: string,
  options?: RequestInit,
): Promise<Job> => {
  return customFetch<Job>(getGetJobByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetJobByIdQueryKey = (id: string) => {
  return [`/api/jobs/${id}`] as const;
};

export const getGetJobByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getJobById>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getJobById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetJobByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getJobById>>> = ({
    signal,
  }) => getJobById(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getJobById>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetJobByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getJobById>>
>;
export type GetJobByIdQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get job details
 */

export function useGetJobById<
  TData = Awaited<ReturnType<typeof getJobById>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getJobById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetJobByIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get jobs posted by the current employer
 */
export const getGetMyJobsUrl = () => {
  return `/api/jobs/my`;
};

export const getMyJobs = async (options?: RequestInit): Promise<Job[]> => {
  return customFetch<Job[]>(getGetMyJobsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMyJobsQueryKey = () => {
  return [`/api/jobs/my`] as const;
};

export const getGetMyJobsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyJobs>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMyJobs>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyJobsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyJobs>>> = ({
    signal,
  }) => getMyJobs({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyJobs>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMyJobsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyJobs>>
>;
export type GetMyJobsQueryError = ErrorType<unknown>;

/**
 * @summary Get jobs posted by the current employer
 */

export function useGetMyJobs<
  TData = Awaited<ReturnType<typeof getMyJobs>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMyJobs>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMyJobsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Swipe on a job (like or pass)
 */
export const getCreateSwipeUrl = () => {
  return `/api/swipes`;
};

export const createSwipe = async (
  swipeRequest: SwipeRequest,
  options?: RequestInit,
): Promise<SwipeResponse> => {
  return customFetch<SwipeResponse>(getCreateSwipeUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(swipeRequest),
  });
};

export const getCreateSwipeMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSwipe>>,
    TError,
    { data: BodyType<SwipeRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSwipe>>,
  TError,
  { data: BodyType<SwipeRequest> },
  TContext
> => {
  const mutationKey = ["createSwipe"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSwipe>>,
    { data: BodyType<SwipeRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createSwipe(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSwipeMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSwipe>>
>;
export type CreateSwipeMutationBody = BodyType<SwipeRequest>;
export type CreateSwipeMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Swipe on a job (like or pass)
 */
export const useCreateSwipe = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSwipe>>,
    TError,
    { data: BodyType<SwipeRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createSwipe>>,
  TError,
  { data: BodyType<SwipeRequest> },
  TContext
> => {
  return useMutation(getCreateSwipeMutationOptions(options));
};

/**
 * @summary Get all matches for the current user
 */
export const getGetMatchesUrl = () => {
  return `/api/matches`;
};

export const getMatches = async (options?: RequestInit): Promise<Match[]> => {
  return customFetch<Match[]>(getGetMatchesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMatchesQueryKey = () => {
  return [`/api/matches`] as const;
};

export const getGetMatchesQueryOptions = <
  TData = Awaited<ReturnType<typeof getMatches>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMatches>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMatchesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMatches>>> = ({
    signal,
  }) => getMatches({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMatches>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMatchesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMatches>>
>;
export type GetMatchesQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get all matches for the current user
 */

export function useGetMatches<
  TData = Awaited<ReturnType<typeof getMatches>>,
  TError = ErrorType<ErrorResponse>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMatches>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMatchesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get applicants for a specific job (employer only)
 */
export const getGetJobApplicantsUrl = (jobId: string) => {
  return `/api/employer/applicants/${jobId}`;
};

export const getJobApplicants = async (
  jobId: string,
  options?: RequestInit,
): Promise<Applicant[]> => {
  return customFetch<Applicant[]>(getGetJobApplicantsUrl(jobId), {
    ...options,
    method: "GET",
  });
};

export const getGetJobApplicantsQueryKey = (jobId: string) => {
  return [`/api/employer/applicants/${jobId}`] as const;
};

export const getGetJobApplicantsQueryOptions = <
  TData = Awaited<ReturnType<typeof getJobApplicants>>,
  TError = ErrorType<ErrorResponse>,
>(
  jobId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getJobApplicants>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetJobApplicantsQueryKey(jobId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getJobApplicants>>
  > = ({ signal }) => getJobApplicants(jobId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!jobId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getJobApplicants>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetJobApplicantsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getJobApplicants>>
>;
export type GetJobApplicantsQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get applicants for a specific job (employer only)
 */

export function useGetJobApplicants<
  TData = Awaited<ReturnType<typeof getJobApplicants>>,
  TError = ErrorType<ErrorResponse>,
>(
  jobId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getJobApplicants>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetJobApplicantsQueryOptions(jobId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Employer swipes on an applicant (approve or reject)
 */
export const getEmployerSwipeUrl = () => {
  return `/api/employer/swipe`;
};

export const employerSwipe = async (
  employerSwipeRequest: EmployerSwipeRequest,
  options?: RequestInit,
): Promise<SwipeResponse> => {
  return customFetch<SwipeResponse>(getEmployerSwipeUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(employerSwipeRequest),
  });
};

export const getEmployerSwipeMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof employerSwipe>>,
    TError,
    { data: BodyType<EmployerSwipeRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof employerSwipe>>,
  TError,
  { data: BodyType<EmployerSwipeRequest> },
  TContext
> => {
  const mutationKey = ["employerSwipe"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof employerSwipe>>,
    { data: BodyType<EmployerSwipeRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return employerSwipe(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EmployerSwipeMutationResult = NonNullable<
  Awaited<ReturnType<typeof employerSwipe>>
>;
export type EmployerSwipeMutationBody = BodyType<EmployerSwipeRequest>;
export type EmployerSwipeMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Employer swipes on an applicant (approve or reject)
 */
export const useEmployerSwipe = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof employerSwipe>>,
    TError,
    { data: BodyType<EmployerSwipeRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof employerSwipe>>,
  TError,
  { data: BodyType<EmployerSwipeRequest> },
  TContext
> => {
  return useMutation(getEmployerSwipeMutationOptions(options));
};
