/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * BeHired API - Tinder-style job matching platform
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface MessageResponse {
  message: string;
}

export type RegisterRequestRole =
  (typeof RegisterRequestRole)[keyof typeof RegisterRequestRole];

export const RegisterRequestRole = {
  jobseeker: "jobseeker",
  employer: "employer",
} as const;

export interface RegisterRequest {
  email: string;
  password: string;
  name: string;
  role: RegisterRequestRole;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export type AuthResponseRole =
  (typeof AuthResponseRole)[keyof typeof AuthResponseRole];

export const AuthResponseRole = {
  jobseeker: "jobseeker",
  employer: "employer",
} as const;

export interface AuthResponse {
  id: string;
  email: string;
  name: string;
  role: AuthResponseRole;
}

export type UserProfileRole =
  (typeof UserProfileRole)[keyof typeof UserProfileRole];

export const UserProfileRole = {
  jobseeker: "jobseeker",
  employer: "employer",
} as const;

export interface UserProfile {
  id: string;
  name: string;
  email: string;
  role: UserProfileRole;
  bio?: string;
  skills?: string[];
  location?: string;
  avatar?: string;
  resumeUrl?: string;
  companyName?: string;
  companyDescription?: string;
  companyWebsite?: string;
  companyLogo?: string;
}

export interface UpdateProfileRequest {
  name?: string;
  bio?: string;
  skills?: string[];
  location?: string;
  avatar?: string;
  resumeUrl?: string;
  companyName?: string;
  companyDescription?: string;
  companyWebsite?: string;
  companyLogo?: string;
}

export type JobType = (typeof JobType)[keyof typeof JobType];

export const JobType = {
  job: "job",
  internship: "internship",
} as const;

export interface Job {
  id: string;
  title: string;
  company: string;
  companyLogo?: string;
  location: string;
  type: JobType;
  salary?: string;
  description: string;
  requirements?: string[];
  tags?: string[];
  employerId: string;
  createdAt: string;
  remote?: boolean;
}

export type CreateJobRequestType =
  (typeof CreateJobRequestType)[keyof typeof CreateJobRequestType];

export const CreateJobRequestType = {
  job: "job",
  internship: "internship",
} as const;

export interface CreateJobRequest {
  title: string;
  company: string;
  companyLogo?: string;
  location: string;
  type: CreateJobRequestType;
  salary?: string;
  description: string;
  requirements?: string[];
  tags?: string[];
  remote?: boolean;
}

export type SwipeRequestDirection =
  (typeof SwipeRequestDirection)[keyof typeof SwipeRequestDirection];

export const SwipeRequestDirection = {
  like: "like",
  pass: "pass",
} as const;

export interface SwipeRequest {
  jobId: string;
  direction: SwipeRequestDirection;
}

export type EmployerSwipeRequestDirection =
  (typeof EmployerSwipeRequestDirection)[keyof typeof EmployerSwipeRequestDirection];

export const EmployerSwipeRequestDirection = {
  like: "like",
  pass: "pass",
} as const;

export interface EmployerSwipeRequest {
  applicantId: string;
  jobId: string;
  direction: EmployerSwipeRequestDirection;
}

export interface SwipeResponse {
  success: boolean;
  matched: boolean;
  message?: string;
}

export type MatchStatus = (typeof MatchStatus)[keyof typeof MatchStatus];

export const MatchStatus = {
  pending: "pending",
  accepted: "accepted",
  rejected: "rejected",
} as const;

export interface Match {
  id: string;
  jobId: string;
  jobTitle: string;
  company: string;
  companyLogo?: string;
  applicantId: string;
  applicantName: string;
  applicantAvatar?: string;
  matchedAt: string;
  status: MatchStatus;
}

export interface Applicant {
  id: string;
  applicantId: string;
  name: string;
  email: string;
  avatar?: string;
  bio?: string;
  skills?: string[];
  location?: string;
  resumeUrl?: string;
  swipedAt: string;
}

export type GetJobsParams = {
  /**
   * Filter by type
   */
  type?: GetJobsType;
  /**
   * Number of results
   */
  limit?: number;
};

export type GetJobsType = (typeof GetJobsType)[keyof typeof GetJobsType];

export const GetJobsType = {
  job: "job",
  internship: "internship",
  all: "all",
} as const;
